export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_SUCCESS = 'AUTH_SUCCES';

export const LOG_OUT = 'LOG_OUT';
export const RESET_ERRORS = 'RESET_ERRORS';

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCES';
